package com.example.diceroll

import android.os.Bundle
import android.widget.Button
import android.widget.ImageView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val diceImage: ImageView = findViewById(R.id.imageView)
        diceImage.setImageResource(R.drawable.dice_1)
        diceImage.contentDescription = "one"
        /**
         * Sets an onClickListener for when the button is pressed. It outputs a Toast
         * that lets the user know the dice has been rolled and updates the textview
         * to show the random number that was generated by pressing the button.
         */
        val rollButton: Button = findViewById(R.id.button)
        rollButton.setOnClickListener {
            //val toast = Toast.makeText(this, "Dice Rolled!", Toast.LENGTH_SHORT).show()
            val roll = rollDice()
            val drawableResource = when (roll) {
                1 -> R.drawable.dice_1
                2 -> R.drawable.dice_2
                3 -> R.drawable.dice_3
                4 -> R.drawable.dice_4
                5 -> R.drawable.dice_5
                else -> R.drawable.dice_6
            }
            diceImage.setImageResource(drawableResource)
            diceImage.contentDescription = roll.toString()
        }
    }

    /**
     * Creates an Dice object and calls the roll function and returns the result.
     */
    private fun rollDice(): Int? {
        val dice = Dice(6)
        return dice.roll()
    }
}

/**
 * Dice class takes in a int that represents the number of side of a dice.
 */
class Dice(private val numSides: Int) {

    /**
     * Defines a roll function that returns a random int based on the number of sides given
     */
    fun roll(): Int {
        return (1..numSides).random()
    }
}